// Переводы для всех языков
const languages = {
    ru: {
        flag: '🇷🇺',
        code: 'RU',
        name: 'Русский',
        title: 'Ставки от AI',
        category: 'Футбол',
        upload: '📸 Загрузите изображение события',
        uploadHint: 'Или просто вставьте скриншот (Ctrl + V)',
        changeImage: '📤 Попробовать другое изображение',
        analyzeBtn: '🔍 Проанализировать ставку',
        analyzing: 'Анализируем...',
        attemptsToday: 'Попыток сегодня:',
        attemptsLeft: 'Осталось попыток на сегодня:',
        confidenceLabel: 'УВЕРЕННОСТЬ AI',
        signalLabel: 'НАДЕЖНЫЙ СИГНАЛ',
        eventsLabel: '% СОБЫТИЙ',
        analyticsLabel: 'AI АНАЛИТИКА',
        unlimited: 'Безлимит'
    },
    en: {
        flag: '🇬🇧',
        code: 'EN',
        name: 'English',
        title: 'AI Betting Analysis',
        category: 'Football',
        upload: '📸 Upload event image',
        uploadHint: 'Or paste a screenshot (Ctrl + V)',
        changeImage: '📤 Try another image',
        analyzeBtn: '🔍 Analyze Bet',
        analyzing: 'Analyzing...',
        attemptsToday: 'Attempts today:',
        attemptsLeft: 'Attempts left today:',
        confidenceLabel: 'AI CONFIDENCE',
        signalLabel: 'RELIABLE SIGNAL',
        eventsLabel: '% EVENTS',
        analyticsLabel: 'AI ANALYTICS',
        unlimited: 'Unlimited'
    },
    hi: {
        flag: '🇮🇳',
        code: 'HI',
        name: 'हिन्दी',
        title: 'AI से दांव',
        category: 'फुटबॉल',
        upload: '📸 कार्यक्रम की छवि अपलोड करें',
        uploadHint: 'या स्क्रीनशॉट पेस्ट करें (Ctrl + V)',
        changeImage: '📤 दूसरी छवि आज़माएं',
        analyzeBtn: '🔍 दांव का विश्लेषण करें',
        analyzing: 'विश्लेषण कर रहे हैं...',
        attemptsToday: 'आज के प्रयास:',
        attemptsLeft: 'आज बचे प्रयास:',
        confidenceLabel: 'AI विश्वास',
        signalLabel: 'विश्वसनीय संकेत',
        eventsLabel: '% घटनाएं',
        analyticsLabel: 'AI विश्लेषण',
        unlimited: 'असीमित'
    },
    br: {
        flag: '🇧🇷',
        code: 'BR',
        name: 'Brazilian',
        title: 'Análise de Apostas AI',
        category: 'Futebol',
        upload: '📸 Carregar imagem do evento',
        uploadHint: 'Ou cole uma captura de tela (Ctrl + V)',
        changeImage: '📤 Tentar outra imagem',
        analyzeBtn: '🔍 Analisar Aposta',
        analyzing: 'Analisando...',
        attemptsToday: 'Tentativas hoje:',
        attemptsLeft: 'Tentativas restantes hoje:',
        confidenceLabel: 'CONFIANÇA AI',
        signalLabel: 'SINAL CONFIÁVEL',
        eventsLabel: '% EVENTOS',
        analyticsLabel: 'ANÁLISE AI',
        unlimited: 'Ilimitado'
    },
    es: {
        flag: '🇪🇸',
        code: 'ES',
        name: 'Español',
        title: 'Análisis de Apuestas AI',
        category: 'Fútbol',
        upload: '📸 Subir imagen del evento',
        uploadHint: 'O pegar una captura de pantalla (Ctrl + V)',
        changeImage: '📤 Probar otra imagen',
        analyzeBtn: '🔍 Analizar Apuesta',
        analyzing: 'Analizando...',
        attemptsToday: 'Intentos hoy:',
        attemptsLeft: 'Intentos restantes hoy:',
        confidenceLabel: 'CONFIANZA AI',
        signalLabel: 'SEÑAL CONFIABLE',
        eventsLabel: '% EVENTOS',
        analyticsLabel: 'ANÁLISIS AI',
        unlimited: 'Ilimitado'
    },
    uz: {
        flag: '🇺🇿',
        code: 'UZ',
        name: "O'zbek",
        title: 'AI Garov Tahlili',
        category: 'Futbol',
        upload: '📸 Tadbir rasmini yuklang',
        uploadHint: 'Yoki ekran tasvirini joylashtiring (Ctrl + V)',
        changeImage: '📤 Boshqa rasmni sinab ko\'ring',
        analyzeBtn: '🔍 Garovni Tahlil Qilish',
        analyzing: 'Tahlil qilmoqda...',
        attemptsToday: 'Bugungi urinishlar:',
        attemptsLeft: 'Bugun qolgan urinishlar:',
        confidenceLabel: 'AI ISHONCH',
        signalLabel: 'ISHONCHLI SIGNAL',
        eventsLabel: '% HODISALAR',
        analyticsLabel: 'AI TAHLIL',
        unlimited: 'Cheksiz'
    },
    az: {
        flag: '🇦🇿',
        code: 'AZ',
        name: 'Azərbaycan',
        title: 'AI Mərc Təhlili',
        category: 'Futbol',
        upload: '📸 Tədbir şəklini yükləyin',
        uploadHint: 'Və ya ekran görüntüsünü yapışdırın (Ctrl + V)',
        changeImage: '📤 Başqa şəkil sınayın',
        analyzeBtn: '🔍 Mərci Təhlil Et',
        analyzing: 'Təhlil edilir...',
        attemptsToday: 'Bu gün cəhdlər:',
        attemptsLeft: 'Bu gün qalan cəhdlər:',
        confidenceLabel: 'AI İNAM',
        signalLabel: 'ETİBARLI SİQNAL',
        eventsLabel: '% HADİSƏLƏR',
        analyticsLabel: 'AI TƏHLİL',
        unlimited: 'Limitsiz'
    },
    tr: {
        flag: '🇹🇷',
        code: 'TR',
        name: 'Türkçe',
        title: 'AI Bahis Analizi',
        category: 'Futbol',
        upload: '📸 Etkinlik görselini yükle',
        uploadHint: 'Veya ekran görüntüsünü yapıştır (Ctrl + V)',
        changeImage: '📤 Başka resim dene',
        analyzeBtn: '🔍 Bahis Analizi',
        analyzing: 'Analiz ediliyor...',
        attemptsToday: 'Bugünkü denemeler:',
        attemptsLeft: 'Bugün kalan denemeler:',
        confidenceLabel: 'AI GÜVEN',
        signalLabel: 'GÜVENİLİR SİNYAL',
        eventsLabel: '% OLAYLAR',
        analyticsLabel: 'AI ANALİZ',
        unlimited: 'Sınırsız'
    },
    pt: {
        flag: '🇵🇹',
        code: 'PT',
        name: 'Português',
        title: 'Análise de Apostas AI',
        category: 'Futebol',
        upload: '📸 Carregar imagem do evento',
        uploadHint: 'Ou colar captura de ecrã (Ctrl + V)',
        changeImage: '📤 Tentar outra imagem',
        analyzeBtn: '🔍 Analisar Aposta',
        analyzing: 'A analisar...',
        attemptsToday: 'Tentativas hoje:',
        attemptsLeft: 'Tentativas restantes hoje:',
        confidenceLabel: 'CONFIANÇA AI',
        signalLabel: 'SINAL CONFIÁVEL',
        eventsLabel: '% EVENTOS',
        analyticsLabel: 'ANÁLISE AI',
        unlimited: 'Ilimitado'
    },
    ar: {
        flag: '🇸🇦',
        code: 'AR',
        name: 'العربية',
        title: 'تحليل المراهنات بالذكاء الاصطناعي',
        category: 'كرة القدم',
        upload: '📸 تحميل صورة الحدث',
        uploadHint: 'أو لصق لقطة شاشة (Ctrl + V)',
        changeImage: '📤 جرب صورة أخرى',
        analyzeBtn: '🔍 تحليل الرهان',
        analyzing: 'جاري التحليل...',
        attemptsToday: 'المحاولات اليوم:',
        attemptsLeft: 'المحاولات المتبقية اليوم:',
        confidenceLabel: 'ثقة الذكاء الاصطناعي',
        signalLabel: 'إشارة موثوقة',
        eventsLabel: '% الأحداث',
        analyticsLabel: 'تحليل الذكاء الاصطناعي',
        unlimited: 'غير محدود'
    }
};
